import { LoaderCircle, RotateCcw, ScanSearch } from 'lucide-react'
import type { AnalysisResult } from '../../types'
import { severityBadgeClass } from '../../utils/severity'
import { Badge } from '../ui/Badge'
import { Button } from '../ui/Button'
import { StepNav } from './StepNav'

type AnalysisStepProps = {
  previewUrl: string | null
  analysis: AnalysisResult | null
  isAnalyzing: boolean
  error: string | null
  onAnalyze: () => void
  onBack: () => void
  onContinue: () => void
}

export function AnalysisStep({
  previewUrl,
  analysis,
  isAnalyzing,
  error,
  onAnalyze,
  onBack,
  onContinue,
}: AnalysisStepProps) {
  return (
    <div>
      {previewUrl ? (
        <div className="mb-5 overflow-hidden rounded-xl border border-slate-200 bg-slate-50">
          <img
            src={previewUrl}
            alt="Photo selected for analysis"
            className="max-h-48 w-full object-contain"
          />
        </div>
      ) : null}

      {isAnalyzing ? (
        <div className="flex flex-col items-center rounded-2xl border border-navy-100 bg-navy-50 px-6 py-12 text-center">
          <LoaderCircle className="h-8 w-8 animate-spin text-navy-800" aria-hidden="true" />
          <p className="mt-4 text-base font-bold text-navy-900">Analyzing photo…</p>
          <p className="mt-1 max-w-sm text-sm text-slate-600">
            Identifying the likely infrastructure issue, category and severity.
          </p>
        </div>
      ) : null}

      {!isAnalyzing && !analysis ? (
        <div className="rounded-2xl border border-slate-200 bg-slate-50 px-6 py-10 text-center">
          <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-white text-navy-800 shadow-sm">
            <ScanSearch className="h-5 w-5" aria-hidden="true" />
          </div>
          <p className="text-base font-bold text-navy-900">Ready for analysis</p>
          <p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">
            BharatFix AI will inspect the photo and suggest the issue type and
            severity. You can adjust the severity in the next step.
          </p>
          {error ? (
            <p className="mx-auto mt-4 max-w-md text-sm font-medium text-severity-high" role="alert">
              {error}
            </p>
          ) : null}
          <Button onClick={onAnalyze} className="mt-6">
            {error ? (
              <RotateCcw className="h-4 w-4" aria-hidden="true" />
            ) : (
              <ScanSearch className="h-4 w-4" aria-hidden="true" />
            )}
            {error ? 'Try Again' : 'Analyze'}
          </Button>
        </div>
      ) : null}

      {analysis ? (
        <article className="rounded-2xl border border-navy-100 bg-white p-5 shadow-sm sm:p-6">
          <div className="mb-4 flex flex-wrap items-center justify-between gap-2">
            <h3 className="text-base font-bold text-navy-900">Analysis result</h3>
            {analysis.isDemo ? (
              <Badge className="border-amber-200 bg-amber-50 text-amber-800">
                Demo AI Analysis
              </Badge>
            ) : (
              <Badge className="border-civic-soft bg-civic-soft/40 text-civic-dark">
                AI Analysis
              </Badge>
            )}
          </div>
          <p className="mb-5 text-sm leading-6 text-slate-600">
            {analysis.isDemo
              ? 'Sample structured data because no AI key is configured on the server. This is not a real model prediction.'
              : 'Generated by an AI vision model. Please review it before submitting.'}
          </p>
          <dl className="grid gap-3 sm:grid-cols-2">
            <ResultItem label="Detected Issue" value={analysis.detectedIssue} />
            <ResultItem label="Category" value={analysis.category} />
            <ResultItem label="Confidence" value={`${analysis.confidence}%`} />
            <div className="rounded-xl border border-slate-100 bg-slate-50 px-4 py-3">
              <dt className="text-xs font-semibold tracking-wide text-slate-500 uppercase">
                Severity
              </dt>
              <dd className="mt-1">
                <span
                  className={`inline-flex rounded-full px-2.5 py-0.5 text-sm font-semibold ${severityBadgeClass[analysis.severity]}`}
                >
                  {analysis.severity}
                </span>
              </dd>
            </div>
          </dl>
        </article>
      ) : null}

      <StepNav
        onBack={onBack}
        onContinue={analysis ? onContinue : undefined}
        continueLabel="Continue"
        hideContinue={!analysis}
        continueDisabled={!analysis || isAnalyzing}
      />
    </div>
  )
}

function ResultItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-slate-100 bg-slate-50 px-4 py-3">
      <dt className="text-xs font-semibold tracking-wide text-slate-500 uppercase">
        {label}
      </dt>
      <dd className="mt-1 text-sm font-bold text-navy-900">{value}</dd>
    </div>
  )
}
